apm_tab.vars={
	allow_prop_damage=0,--decide if players can be lose health or die from prop damage
	allow_vehicle_damage=1,--decide if players can be lose health or die from getting hit by vehicles
	allow_world_damage=0,--decide if players can be lose health or die from world damage
	freeze_all_anonymity=0,--decides if freezall is annonymous to non admins
	freeze_on_damage=1,--decide whether to freeze a player's props if they damage someone
	nocollide_all_vehicles=0,--how oftem should we check for cars that are not nocollided? set to 0 to disable
	nocollide_on_prop_damage=0,--decide whether to nocollide a player's prop if it damages someone
	nocollide_on_vehicle_damage=0,--decide whether to nocollide a player's car if it damages someone
	notify_on_damage=1,--decide whether to notify admins if someone is damaged by a prop
	notify_on_vehicle_damage=0,--decide whether to notify admins if someone is damaged by a vehicle
	map_ents_bypass=1,--are map ents allowed to damage players?
	print_damage_info=0,--decide whether to print the damage info for debuging purposes
	prop_suicide_notification=1,--decide whether to notify admins if someone is killed by their own prop
	remove_on_damage=1,--decide whether to remove a player's prop if it damages someone
	strict_damage_check=0,--decide if we use strict damage checks,it will block ALL sources of crush damage
	unfreeze_ent_delay=1,--how many seconds must a player wait between using physgun?
	unfreeze_ent_limit=10,--how many enitites can be unfrozen at once using physgun reload?
}