if SERVER then
	include("freeze_everything.lua")
	include("freeze_my_props.lua")
	include("propkill_hook.lua")
	include("prop_damage_hook.lua")
	include("vehicle_damage_hook.lua")
	include("apm_util.lua")
	include("strict_damage_check.lua")
	include("prop_removal.lua")
	include("physgun_reload_limiter.lua")

	CreateConVar("apm_nocollide_all_vehicles", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "how oftem should we check for cars that are not nocollided? set to 0 to disable")
	CreateConVar("apm_freeze_all_anonymity", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decides if freezall is annonymous to non admins")
	CreateConVar("apm_prop_suicide_notification", "1", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to notify admins if someone is killed by their own prop")
	CreateConVar("apm_notify_on_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to notify admins if someone is damaged by a prop")
	CreateConVar("apm_freeze_on_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to freeze a player's props if they damage someone")
	CreateConVar("apm_allow_prop_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide if players can be lose health or die from prop damage")
	CreateConVar("apm_allow_world_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide if players can be lose health or die from world damage")
	CreateConVar("apm_allow_vehicle_damage", "1", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide if players can be lose health or die from getting hit by vehicles")
	CreateConVar("apm_notify_on_vehicle_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to notify admins if someone is damaged by a vehicle")
	CreateConVar("apm_strict_damage_check", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide if we use strict damage checks, it will block ALL sources of crush damage")
	CreateConVar("apm_remove_on_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to remove a player's prop if it damages someone")
	CreateConVar("apm_print_damage_info", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to print the damage info for debuging purposes")
	CreateConVar("apm_nocollide_on_prop_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to nocollide a player's prop if it damages someone")
	CreateConVar("apm_nocollide_on_vehicle_damage", "0", {FCVAR_ARCHIVE, FCVAR_SERVER_CAN_EXECUTE}, "decide whether to nocollide a player's car if it damages someone")
	CreateConVar("apm_unfreeze_ent_delay","1",FCVAR_ARCHIVE,FCVAR_SERVER_CAN_EXECUTE,FCVAR_REPLICATED,"how many seconds must a player wait between using physgun?"):GetFloat()
	CreateConVar("apm_unfreeze_ent_limit","10",FCVAR_ARCHIVE,FCVAR_SERVER_CAN_EXECUTE,FCVAR_REPLICATED,"how many enitites can be unfrozen at once using physgun reload?"):GetInt()
end